language: node_js
node_js:
  - "8"
before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FA_AUTH_TOKEN}" >> ~/.npmrc
  - printf "export default { cyclomedia: { test1: 'test' }}" >> ~/src/topicsmap_file.js
script: npm run build
before_deploy:
  - rm -rf node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'topicsmap'
    on:
      branch: master
    local_dir: dist
    skip_cleanup: true
