language: node_js
node_js:
  - "8"
script: npm run build
before_deploy:
  - rm -rf node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'topicmaps'
    on:
      branch: master
    local_dir: dist
    skip_cleanup: true
